### PR TITLE
fix: lint dirty modules

### PR DESCRIPTION
**Pull request by LingyuCoder**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Use `compilation.builtModules` to collect changed modules when `lintOnlyDirtyModules` is enabled

### CODE REVIEW

**Comment by LingyuCoder** [comment]
Should upgrade dependencies with security issue, I will do it in another pr

**Review by 9aoy — APPROVED** [review]

**Comment by markmssd** [comment]
I've tested it and seems to be working now, with Rspack v1.0.8 🎉 It has the exact behaviour as Webpack now, thanks! When do you think we can have a new release of this plugin?

**Comment by LingyuCoder** [comment]
> I've tested it and seems to be working now, with Rspack v1.0.8 🎉 It has the exact behaviour as Webpack now, thanks! When do you think we can have a new release of this plugin?

Published v4.2.1, please have a try 😊

**Comment by nanianlisao** [comment]
@LingyuCoder @9aoy 
Can compatibility with rspack0.x be added? Only rspack 1.0 supports the seal hook.

**Pull request merged**
